name: Check the lidar2feature core functions

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          conda install --file conda-requirements.txt -y --channel conda-forge
          pip install -r pip-requirements.txt
      - name: Run against the functions
        run: |
          python lidar2feature-test.py